### PR TITLE
Use CMake

### PR DESCRIPTION
**Pull request by SfietKonstantin**

### CODE REVIEW

**Comment by SfietKonstantin** [comment]
@stskeeps @siteshwar mind reviewing and check the build ?

**Comment by SfietKonstantin** [comment]
Not ready to merge. CMake is failing to static link everything. Investigating

**Comment by SfietKonstantin** [comment]
Ready for merge now
I have tested with Linux. Under Windows, we might need to add some SSL lib and zlib as dependencies

**Comment by siteshwar** [comment]
Ship it!

**Pull request merged**
